#CONFIGURACION DE RUTAS DE PROYECTO

from pathlib import Path

#APUNTA A LA CARPETA "Datos" UBICADA JUNTO CON ESTE PROYECTO
DIRECTORIO_BASE = Path("../Datos") 

#APUNTA A LA CARPETA "Recursos" UBICADA JUNTO CON ESTE PROYECTO
RECURSOS = Path("../Recursos")

#DECLARACION DE RUTAS DE CARPETAS
CARGADOS = DIRECTORIO_BASE / "Cargados"
PROCESADOS = DIRECTORIO_BASE / "Procesados"
CSV_GENERADOS = DIRECTORIO_BASE / "CSV_Generados"
IMPLEMENTACION_GOBERNANZA = DIRECTORIO_BASE / "Implementacion_Gobernaza"
ANALITICOS_PARQUET = DIRECTORIO_BASE / "Analiticos" / "Parquet"
ANALITICOS_RESULTADOS = DIRECTORIO_BASE / "Analiticos" / "Resultados"

#LISTA DE RUTAS PARA CREAR CARPETAS SEGEMENTADAS
modelo_carpetas = [
    CARGADOS, PROCESADOS, CSV_GENERADOS,
    IMPLEMENTACION_GOBERNANZA, ANALITICOS_PARQUET, ANALITICOS_RESULTADOS
]

#CREACION DE CARPETAS
for modelo_carpeta in modelo_carpetas:
    modelo_carpeta.mkdir(parents=True, exist_ok=True)